CREATE DATABASE TestTask
GO

CREATE TABLE TOV(
	KTOV VARCHAR(10) PRIMARY KEY,
	NTOV VARCHAR(60),
	SORT VARCHAR(10)
)

GO

CREATE TABLE DMZ(
	
	DDM DATE,
	NDM INT PRIMARY KEY,
	PR INT,

)

GO

CREATE TABLE DMS(
	KTOV VARCHAR(10),
	KOL DECIMAL(13,2),
	CENA DECIMAL(13,2),
	SORT CHAR(10),
	DMZ_ID INT FOREIGN KEY REFERENCES DMZ,
	TOV_ID VARCHAR(10) FOREIGN KEY REFERENCES TOV,
)

GO

--1.
--2. Sort зберігається у двох таблицях одразу, що є порушенням другої нормальної форми.
--тобто видаливши інформацію про товар інформація про вид товару також буде втрачена.
--теж саме із кодом товару

--3.
--3.1
CREATE PROCEDURE SelectSalesPerDay @Date date
AS
SELECT NTOV, SUM(KOL) AS S, SUM(CENA*KOL)
FROM DMS 
INNER JOIN TOV ON TOV.KTOV = DMS.TOV_ID
INNER JOIN DMZ ON DMS.DMZ_ID = DMZ.NDM
WHERE DMZ.DDM = @Date
ORDER BY Sum(KOL) DESC;

--3.2 ...
UPDATE DMS
SET SORT = 
(SELECT TOV.SORT 
FROM TOV 
INNER JOIN DMS ON DMS.KTOV = TOV.KTOV)
--3.3

GO
SELECT DISTINCT NTOV,
KOL - (SELECT KOL
FROM DMS
INNER JOIN DMZ ON DMS.DMZ_ID = DMZ.NDM
WHERE PR = 2),
KOL* CENA - (SELECT KOL * CENA
FROM DMS
INNER JOIN DMZ ON DMS.DMZ_ID = DMZ.NDM
WHERE PR = 2)
FROM DMS
INNER JOIN DMZ ON DMS.DMZ_ID = DMZ.NDM
INNER JOIN TOV ON TOV.KTOV = DMS.TOV_ID 
WHERE PR = 1;

GO

--3.4
INSERT INTO DMZ (DDM,PR)
VALUES(
		((SELECT TOP 1 NDM FROM DMZ ORDER BY NDM DESC) + 1),
		--в цьому нема сенсу 
		--тк поле є приватним ключем і sql server сам інкрементує дане значення
		--але можливо я не так щось зрозумів тому хай буде :d
		(SELECT CAST( GETDATE() AS Date)),
		( CASE 
		WHEN (SELECT COUNT(*) FROM DMZ WHERE PR = 1) < (SELECT COUNT(*) FROM DMZ WHERE PR = 2)
		THEN  1
		ELSE 2
		END))

GO
--3.5
INSERT INTO DMS (KTOV, KOL,CENA,SORT, DMZ_ID)
SELECT KTOV, KOL,CENA,SORT, (SELECT TOP 1 NDM FROM DMZ ORDER BY NDM DESC)
FROM DMZ 
INNER JOIN DMS ON DMS.DMZ_ID = DMZ.NDM
WHERE DMZ.NDM = (SELECT TOP 1 NDM FROM DMZ ORDER BY NDM)
AND DMS.SORT not in (SELECT SORT FROM DMZ 
INNER JOIN DMS ON DMS.DMZ_ID = DMZ.NDM 
);







